### ISSUE TITLE
Integration seems to cripple resources.. is this normal ?

### ISSUE THREAD

**Issue by mbarne36** [yohaybn/HomeAssistant-EPG#1]
Hi.

I installed this integration a week or so ago and it works for me - to a point. I find that it cripples resources and slows the HA down. When on the weburl it takes ages to move between pages. I just commented out the integration in configuration.yaml and previous responsiveness returned after the reboot.

Is this normal? I am just surprised if it is because when I look at the code it only seems to pull the new EPG once per day, so I can't figure out what its doing in the background.

thanks for assist.

**Comment by yohaybn** [comment]
Hi. 
I never see that behavior before.
I know that it's take time to load but it's once a day.
Can you tell what is your hardware spec and what file you try to load?
