### ISSUE TITLE
Support open-epg?

### ISSUE THREAD

**Issue by Keysersose12** [yohaybn/HomeAssistant-EPG#7]
Is it possible to now support open-epg.com? since it looks to have replaced bevy.be going by their website.

**Comment by yohaybn** [comment]
Hi @Keysersose12 ,

Thanks for letting me know about open-epg.com! You're correct – bevy.be has transitioned their services.

I've implemented support for open-epg.com in the latest integration update.
Simply updating the integration is all you need to do
Thanks again for the heads-up! Let me know if you have any questions.
